// Datos de ejemplo para los carruseles de recetas de la home. No vienen de la API
// todavía: se usan solo para mostrar el diseño hasta que exista la feature de recetas
// real (mismo criterio que features/landing/models/landingMockData.js para la landing).
// Cada carrusel tiene ~15 recetas a propósito: son las que hacen falta para poder
// probar que el loop infinito funciona (con 2 o 3 no se nota si realmente da la vuelta).

// Crea un objeto receta de muestra con valores por defecto sobreescribibles.
// Recibe: un objeto parcial con los campos a fijar. Devuelve: la receta completa.
const createMockHomeRecipe = (overrides) => ({
  id: null,
  title: '',
  image: '',
  badge: null,
  // Si description está presente, la card la muestra en vez del tiempo/dificultad.
  description: null,
  time: null,
  difficulty: null,
  author: null,
  authorAvatar: null,
  ...overrides,
});

export const quickRecipes = [
  createMockHomeRecipe({
    id: 'milanesa-napolitana',
    title: 'Milanesa Napolitana',
    image: 'https://picsum.photos/seed/chefcito-milanesa/480/360',
    badge: { label: 'Nuevo' },
    time: '45 min',
    difficulty: 'Fácil',
    author: 'Don Carlos',
    authorAvatar: 'https://picsum.photos/seed/chefcito-user-carlos/48/48',
  }),
  createMockHomeRecipe({
    id: 'pasta-casera',
    title: 'Pasta Casera',
    image: 'https://picsum.photos/seed/chefcito-pasta-casera/480/360',
    time: '1 hr 20 min',
    difficulty: 'Media',
    author: 'Lucía M.',
    authorAvatar: 'https://picsum.photos/seed/chefcito-user-lucia/48/48',
  }),
  createMockHomeRecipe({
    id: 'tostadas-con-palta',
    title: 'Tostadas con Palta',
    image: 'https://picsum.photos/seed/chefcito-tostadas/480/360',
    time: '10 min',
    difficulty: 'Fácil',
    author: 'Marina R.',
    authorAvatar: 'https://picsum.photos/seed/chefcito-user-marina/48/48',
  }),
  createMockHomeRecipe({
    id: 'huevos-revueltos',
    title: 'Huevos Revueltos',
    image: 'https://picsum.photos/seed/chefcito-huevos/480/360',
    time: '8 min',
    difficulty: 'Fácil',
    author: 'Julián P.',
    authorAvatar: 'https://picsum.photos/seed/chefcito-user-julian/48/48',
  }),
  createMockHomeRecipe({
    id: 'sandwich-de-milanesa',
    title: 'Sándwich de Milanesa',
    image: 'https://picsum.photos/seed/chefcito-sandwich/480/360',
    time: '15 min',
    difficulty: 'Fácil',
    author: 'Sofía G.',
    authorAvatar: 'https://picsum.photos/seed/chefcito-user-sofia-g/48/48',
  }),
  createMockHomeRecipe({
    id: 'wok-de-vegetales',
    title: 'Wok de Vegetales',
    image: 'https://picsum.photos/seed/chefcito-wok-veg/480/360',
    time: '18 min',
    difficulty: 'Fácil',
    author: 'Ana B.',
    authorAvatar: 'https://picsum.photos/seed/chefcito-user-ana/48/48',
  }),
  createMockHomeRecipe({
    id: 'tortilla-de-papas',
    title: 'Tortilla de Papas',
    image: 'https://picsum.photos/seed/chefcito-tortilla/480/360',
    time: '30 min',
    difficulty: 'Media',
    author: 'Carlos D.',
    authorAvatar: 'https://picsum.photos/seed/chefcito-user-carlos-d/48/48',
  }),
  createMockHomeRecipe({
    id: 'omelette-de-queso',
    title: 'Omelette de Queso',
    image: 'https://picsum.photos/seed/chefcito-omelette/480/360',
    time: '12 min',
    difficulty: 'Fácil',
    author: 'Valentina R.',
    authorAvatar: 'https://picsum.photos/seed/chefcito-user-valentina/48/48',
  }),
  createMockHomeRecipe({
    id: 'pizza-casera',
    title: 'Pizza Casera',
    image: 'https://picsum.photos/seed/chefcito-pizza/480/360',
    time: '25 min',
    difficulty: 'Media',
    author: 'Mateo F.',
    authorAvatar: 'https://picsum.photos/seed/chefcito-user-mateo/48/48',
  }),
  createMockHomeRecipe({
    id: 'ensalada-cesar',
    title: 'Ensalada César',
    image: 'https://picsum.photos/seed/chefcito-cesar/480/360',
    time: '15 min',
    difficulty: 'Fácil',
    author: 'Camila S.',
    authorAvatar: 'https://picsum.photos/seed/chefcito-user-camila/48/48',
  }),
  createMockHomeRecipe({
    id: 'fideos-con-manteca',
    title: 'Fideos con Manteca',
    image: 'https://picsum.photos/seed/chefcito-fideos/480/360',
    time: '20 min',
    difficulty: 'Fácil',
    author: 'Tomás L.',
    authorAvatar: 'https://picsum.photos/seed/chefcito-user-tomas/48/48',
  }),
  createMockHomeRecipe({
    id: 'arroz-con-pollo',
    title: 'Arroz con Pollo',
    image: 'https://picsum.photos/seed/chefcito-arroz-pollo/480/360',
    time: '40 min',
    difficulty: 'Media',
    author: 'Martina V.',
    authorAvatar: 'https://picsum.photos/seed/chefcito-user-martina/48/48',
  }),
  createMockHomeRecipe({
    id: 'quesadillas',
    title: 'Quesadillas',
    image: 'https://picsum.photos/seed/chefcito-quesadillas/480/360',
    time: '10 min',
    difficulty: 'Fácil',
    author: 'Nicolás H.',
    authorAvatar: 'https://picsum.photos/seed/chefcito-user-nicolas/48/48',
  }),
  createMockHomeRecipe({
    id: 'sopa-de-verduras',
    title: 'Sopa de Verduras',
    image: 'https://picsum.photos/seed/chefcito-sopa/480/360',
    time: '35 min',
    difficulty: 'Media',
    author: 'Florencia N.',
    authorAvatar: 'https://picsum.photos/seed/chefcito-user-florencia/48/48',
  }),
  createMockHomeRecipe({
    id: 'tacos-de-carne',
    title: 'Tacos de Carne',
    image: 'https://picsum.photos/seed/chefcito-tacos/480/360',
    time: '20 min',
    difficulty: 'Fácil',
    author: 'Agustín T.',
    authorAvatar: 'https://picsum.photos/seed/chefcito-user-agustin/48/48',
  }),
];

export const trendingRecipes = [
  createMockHomeRecipe({
    id: 'locro-tradicional',
    title: 'Locro Tradicional',
    image: 'https://picsum.photos/seed/chefcito-locro/480/360',
    description: 'El clásico guiso argentino.',
  }),
  createMockHomeRecipe({
    id: 'empanadas-saltenas',
    title: 'Empanadas Salteñas',
    image: 'https://picsum.photos/seed/chefcito-empanadas/480/360',
    description: 'Al horno de barro.',
  }),
  createMockHomeRecipe({
    id: 'milanesas-de-pollo',
    title: 'Milanesas de Pollo',
    image: 'https://picsum.photos/seed/chefcito-milanesas-pollo/480/360',
    description: 'Crocantes por fuera, jugosas por dentro.',
  }),
  createMockHomeRecipe({
    id: 'asado-criollo',
    title: 'Asado Criollo',
    image: 'https://picsum.photos/seed/chefcito-asado/480/360',
    description: 'El infaltable de los domingos.',
  }),
  createMockHomeRecipe({
    id: 'choripan',
    title: 'Choripán',
    image: 'https://picsum.photos/seed/chefcito-choripan/480/360',
    description: 'Ideal para compartir.',
  }),
  createMockHomeRecipe({
    id: 'provoleta',
    title: 'Provoleta',
    image: 'https://picsum.photos/seed/chefcito-provoleta/480/360',
    description: 'Entrada infalible a la parrilla.',
  }),
  createMockHomeRecipe({
    id: 'guiso-de-lentejas',
    title: 'Guiso de Lentejas',
    image: 'https://picsum.photos/seed/chefcito-lentejas/480/360',
    description: 'Reconfortante para el invierno.',
  }),
  createMockHomeRecipe({
    id: 'noquis-del-29',
    title: 'Ñoquis del 29',
    image: 'https://picsum.photos/seed/chefcito-noquis/480/360',
    description: 'Tradición de fin de mes.',
  }),
  createMockHomeRecipe({
    id: 'bife-a-la-criolla',
    title: 'Bife a la Criolla',
    image: 'https://picsum.photos/seed/chefcito-bife/480/360',
    description: 'Con salsa casera de tomate.',
  }),
  createMockHomeRecipe({
    id: 'matambre-a-la-pizza',
    title: 'Matambre a la Pizza',
    image: 'https://picsum.photos/seed/chefcito-matambre/480/360',
    description: 'Un clásico reinventado.',
  }),
  createMockHomeRecipe({
    id: 'carbonada',
    title: 'Carbonada',
    image: 'https://picsum.photos/seed/chefcito-carbonada/480/360',
    description: 'Guiso dulce y salado.',
  }),
  createMockHomeRecipe({
    id: 'humita-en-chala',
    title: 'Humita en Chala',
    image: 'https://picsum.photos/seed/chefcito-humita/480/360',
    description: 'Sabor a campo.',
  }),
  createMockHomeRecipe({
    id: 'sorrentinos',
    title: 'Sorrentinos de Jamón y Queso',
    image: 'https://picsum.photos/seed/chefcito-sorrentinos/480/360',
    description: 'Rellenos y caseros.',
  }),
  createMockHomeRecipe({
    id: 'vitel-tone',
    title: 'Vitel Toné',
    image: 'https://picsum.photos/seed/chefcito-vitel-tone/480/360',
    description: 'Ideal para las fiestas.',
  }),
  createMockHomeRecipe({
    id: 'pastel-de-papa',
    title: 'Pastel de Papa',
    image: 'https://picsum.photos/seed/chefcito-pastel-papa/480/360',
    description: 'Comfort food de siempre.',
  }),
];

export const veganRecipes = [
  createMockHomeRecipe({
    id: 'buddha-bowl-vegano',
    title: 'Buddha Bowl Vegano',
    image: 'https://picsum.photos/seed/chefcito-buddha-bowl/480/360',
    description: 'Nutritivo y colorido.',
  }),
  createMockHomeRecipe({
    id: 'ensalada-de-estacion',
    title: 'Ensalada de Estación',
    image: 'https://picsum.photos/seed/chefcito-ensalada/480/360',
    description: 'Vegetales asados y semillas.',
  }),
  createMockHomeRecipe({
    id: 'milanesas-de-berenjena',
    title: 'Milanesas de Berenjena',
    image: 'https://picsum.photos/seed/chefcito-berenjena/480/360',
    description: 'Crocantes y sin carne.',
  }),
  createMockHomeRecipe({
    id: 'hamburguesa-de-lentejas',
    title: 'Hamburguesa de Lentejas',
    image: 'https://picsum.photos/seed/chefcito-hamburguesa-lentejas/480/360',
    description: 'Proteína vegetal con mucho sabor.',
  }),
  createMockHomeRecipe({
    id: 'curry-de-garbanzos',
    title: 'Curry de Garbanzos',
    image: 'https://picsum.photos/seed/chefcito-curry/480/360',
    description: 'Especiado y cremoso.',
  }),
  createMockHomeRecipe({
    id: 'tarta-de-espinaca-vegana',
    title: 'Tarta de Espinaca Vegana',
    image: 'https://picsum.photos/seed/chefcito-tarta-espinaca/480/360',
    description: 'Sin lácteos ni huevo.',
  }),
  createMockHomeRecipe({
    id: 'risotto-de-hongos',
    title: 'Risotto de Hongos',
    image: 'https://picsum.photos/seed/chefcito-risotto/480/360',
    description: 'Cremoso a base de caldo vegetal.',
  }),
  createMockHomeRecipe({
    id: 'wok-de-tofu',
    title: 'Wok de Tofu y Vegetales',
    image: 'https://picsum.photos/seed/chefcito-wok-tofu/480/360',
    description: 'Rápido y liviano.',
  }),
  createMockHomeRecipe({
    id: 'sopa-de-calabaza',
    title: 'Sopa de Calabaza',
    image: 'https://picsum.photos/seed/chefcito-calabaza/480/360',
    description: 'Ideal para los días fríos.',
  }),
  createMockHomeRecipe({
    id: 'falafel-casero',
    title: 'Falafel Casero',
    image: 'https://picsum.photos/seed/chefcito-falafel/480/360',
    description: 'Crocante por fuera, suave por dentro.',
  }),
  createMockHomeRecipe({
    id: 'guacamole-con-nachos',
    title: 'Guacamole con Nachos',
    image: 'https://picsum.photos/seed/chefcito-guacamole/480/360',
    description: 'Perfecto para compartir.',
  }),
  createMockHomeRecipe({
    id: 'arroz-yamani-con-verduras',
    title: 'Arroz Yamaní con Verduras',
    image: 'https://picsum.photos/seed/chefcito-yamani/480/360',
    description: 'Integral y nutritivo.',
  }),
  createMockHomeRecipe({
    id: 'brownie-vegano',
    title: 'Brownie Vegano',
    image: 'https://picsum.photos/seed/chefcito-brownie/480/360',
    description: 'Sin manteca ni huevo, igual de rico.',
  }),
  createMockHomeRecipe({
    id: 'ceviche-de-palmitos',
    title: 'Ceviche de Palmitos',
    image: 'https://picsum.photos/seed/chefcito-ceviche/480/360',
    description: 'Fresco y cítrico.',
  }),
  createMockHomeRecipe({
    id: 'pad-thai-vegano',
    title: 'Pad Thai Vegano',
    image: 'https://picsum.photos/seed/chefcito-pad-thai/480/360',
    description: 'El clásico tailandés sin carne.',
  }),
];
